import json
import numpy as np
from PIL import Image
from typing import List, Any
import re
from verl.workers.reward.sam_wrapper import SAMWrapper
import base64
from io import BytesIO

_EPS = np.spacing(1)    # the different implementation of epsilon (extreme min value) between numpy and matlab
_TYPE = np.float64
RESIZE_SIZE = (768, 768)



def base64_to_pil(b64_string: str) -> Image.Image:
    """将 Base64 字符串解码回 PIL Image 对象"""
    img_bytes = base64.b64decode(b64_string)
    return Image.open(BytesIO(img_bytes))

class Smeasure(object):
    def __init__(self, alpha: float = 0.5):
        """
        S-measure(Structure-measure) of SOD.
        ::
            @inproceedings{Smeasure,
                title={Structure-measure: A new way to eval foreground maps},
                author={Fan, Deng-Ping and Cheng, Ming-Ming and Liu, Yun and Li, Tao and Borji, Ali},
                booktitle=ICCV,
                pages={4548--4557},
                year={2017}
            }
        :param alpha: the weight for balancing the object score and the region score
        """
        self.sms = []
        self.alpha = alpha

    def step(self, pred: np.ndarray, gt: np.ndarray):
        pred, gt = _prepare_data(pred=pred, gt=gt)

        sm = self.cal_sm(pred, gt)
        self.sms.append(sm)

    def cal_sm(self, pred: np.ndarray, gt: np.ndarray) -> float:
        """
        Calculate the S-measure.
        :return: s-measure
        """
        y = np.mean(gt)
        if y == 0:
            sm = 1 - np.mean(pred)
        elif y == 1:
            sm = np.mean(pred)
        else:
            sm = self.alpha * self.object(pred, gt) + (1 - self.alpha) * self.region(pred, gt)
            sm = max(0, sm)
        return sm

    def object(self, pred: np.ndarray, gt: np.ndarray) -> float:
        """
        Calculate the object score.
        """
        fg = pred * gt
        bg = (1 - pred) * (1 - gt)
        u = np.mean(gt)
        object_score = u * self.s_object(fg, gt) + (1 - u) * self.s_object(bg, 1 - gt)
        return object_score

    def s_object(self, pred: np.ndarray, gt: np.ndarray) -> float:
        x = np.mean(pred[gt == 1])
        sigma_x = np.std(pred[gt == 1], ddof=1)
        score = 2 * x / (np.power(x, 2) + 1 + sigma_x + _EPS)
        return score

    def region(self, pred: np.ndarray, gt: np.ndarray) -> float:
        """
        Calculate the region score.
        """
        x, y = self.centroid(gt)
        part_info = self.divide_with_xy(pred, gt, x, y)
        w1, w2, w3, w4 = part_info["weight"]
        # assert np.isclose(w1 + w2 + w3 + w4, 1), (w1 + w2 + w3 + w4, pred.mean(), gt.mean())

        pred1, pred2, pred3, pred4 = part_info["pred"]
        gt1, gt2, gt3, gt4 = part_info["gt"]
        score1 = self.ssim(pred1, gt1)
        score2 = self.ssim(pred2, gt2)
        score3 = self.ssim(pred3, gt3)
        score4 = self.ssim(pred4, gt4)

        return w1 * score1 + w2 * score2 + w3 * score3 + w4 * score4

    def centroid(self, matrix: np.ndarray) -> tuple:
        """
        To ensure consistency with the matlab code, one is added to the centroid coordinate,
        so there is no need to use the redundant addition operation when dividing the region later,
        because the sequence generated by ``1:X`` in matlab will contain ``X``.
        :param matrix: a bool data array
        :return: the centroid coordinate
        """
        h, w = matrix.shape
        area_object = np.count_nonzero(matrix)
        if area_object == 0:
            x = np.round(w / 2)
            y = np.round(h / 2)
        else:
            # More details can be found at: https://www.yuque.com/lart/blog/gpbigm
            y, x = np.argwhere(matrix).mean(axis=0).round()
        return int(x) + 1, int(y) + 1

    def divide_with_xy(self, pred: np.ndarray, gt: np.ndarray, x: int, y: int) -> dict:
        """
        Use (x,y) to divide the ``pred`` and the ``gt`` into four submatrices, respectively.
        """
        h, w = gt.shape
        area = h * w

        gt_LT = gt[0:y, 0:x]
        gt_RT = gt[0:y, x:w]
        gt_LB = gt[y:h, 0:x]
        gt_RB = gt[y:h, x:w]

        pred_LT = pred[0:y, 0:x]
        pred_RT = pred[0:y, x:w]
        pred_LB = pred[y:h, 0:x]
        pred_RB = pred[y:h, x:w]

        w1 = x * y / area
        w2 = y * (w - x) / area
        w3 = (h - y) * x / area
        w4 = 1 - w1 - w2 - w3

        return dict(
            gt=(gt_LT, gt_RT, gt_LB, gt_RB),
            pred=(pred_LT, pred_RT, pred_LB, pred_RB),
            weight=(w1, w2, w3, w4),
        )

    def ssim(self, pred: np.ndarray, gt: np.ndarray) -> float:
        """
        Calculate the ssim score.
        """
        h, w = pred.shape
        N = h * w

        x = np.mean(pred)
        y = np.mean(gt)

        sigma_x = np.sum((pred - x) ** 2) / (N - 1)
        sigma_y = np.sum((gt - y) ** 2) / (N - 1)
        sigma_xy = np.sum((pred - x) * (gt - y)) / (N - 1)

        alpha = 4 * x * y * sigma_xy
        beta = (x ** 2 + y ** 2) * (sigma_x + sigma_y)

        if alpha != 0:
            score = alpha / (beta + _EPS)
        elif alpha == 0 and beta == 0:
            score = 1
        else:
            score = 0
        return score

    def get_results(self) -> dict:
        """
        Return the results about S-measure.
        :return: dict(sm=sm)
        """
        sm = np.mean(np.array(self.sms, dtype=_TYPE))
        return dict(sm=sm)

def _prepare_data(pred: np.ndarray, gt: np.ndarray) -> tuple:
    """
    Prepare prediction and GT mask for S-measure calculation.

    - pred: normalize to [0,1] (like Matlab mapminmax)
    - gt: ensure binary (0/1) mask

    :param pred: prediction array (uint8 or float)
    :param gt: ground-truth mask (uint8, float, or bool)
    :return: tuple (pred, gt), both float64
    """
    # --- GT ---
    # 如果 GT 已经是 bool 或 0/1，直接转 float64
    if gt.dtype == np.bool_ or (gt.max() <= 1 and gt.min() >= 0):
        gt_bin = gt.astype(_TYPE)
    else:
        # 二值化阈值 127（适合保存为 0/255 的灰度图）
        gt_bin = (gt > 127).astype(_TYPE)

    # --- Prediction ---
    pred = pred.astype(np.float64)
    if pred.max() != pred.min():
        pred = (pred - pred.min()) / (pred.max() - pred.min())
    else:
        pred = np.zeros_like(pred, dtype=_TYPE)

    return pred, gt_bin



def seg_reward(pred_bbox: list, ground_truth: str, sam_model, sm_calculator) -> float:
    """
    Compute segmentation reward based on SAM prediction and GT mask.
    
    pred_bbox: [x1, y1, x2, y2]
    ground_truth: JSON string, e.g. 
                {"bbox": [...],
                 "mask_b64": "...",
                 "image_b64": "..."}
    sam_model: initialized SAMWrapper instance
    """
    if not isinstance(pred_bbox, (list, tuple)) or len(pred_bbox) != 4:
        return 0.0

    try:
        gt_json = json.loads(ground_truth)
        mask_pil = base64_to_pil(gt_json["mask_b64"])
        image_pil = base64_to_pil(gt_json["image_b64"])

        if not mask_pil or not image_pil:
            return 0.0

        # SAM predict
        sam_model.set_image(image_pil)
        mask_pred, _ = sam_model.predict(pred_bbox)

        mask_pred = np.array(mask_pred).astype(_TYPE)

        # load GT mask
        gt_np = (np.array(mask_pil) > 127).astype(_TYPE)
        mask_pred, gt_np = _prepare_data(mask_pred, gt_np)
        
        sm = sm_calculator.cal_sm(mask_pred, gt_np)
        sm_reward = max(0.0, min(1.0, sm))
        return sm_reward
    
    except Exception:
        return 0.0

def bbox_reward(predict_bbox: list, ground_truth: str) -> float:
    """
    Compute IoU between predicted bbox and ground-truth bbox.
    predict_bbox: [x1, y1, x2, y2]
    ground_truth: JSON string, e.g. "[x1, y1, x2, y2]" or '{"bbox": [x1,y1,x2,y2]}'
    """
    if not isinstance(predict_bbox, (list, tuple)) or len(predict_bbox) != 4:
        return 0.0

    try:
        gt_json = json.loads(ground_truth)
        if isinstance(gt_json, dict):
            gt_box = gt_json.get("bbox", [])
        if not isinstance(gt_box, list) or len(gt_box) != 4:
            return 0.0

        xA = max(predict_bbox[0], gt_box[0])
        yA = max(predict_bbox[1], gt_box[1])
        xB = min(predict_bbox[2], gt_box[2])
        yB = min(predict_bbox[3], gt_box[3])

        inter_area = max(0, xB - xA) * max(0, yB - yA)
        boxA_area = (predict_bbox[2] - predict_bbox[0]) * (predict_bbox[3] - predict_bbox[1])
        boxB_area = (gt_box[2] - gt_box[0]) * (gt_box[3] - gt_box[1])
        union_area = boxA_area + boxB_area - inter_area
        return inter_area / union_area if union_area > 0 else 0.0

    except Exception:
        return 0.0

def get_pred_bbox(predict: str) -> float:
    ANSWER_PATTERN = re.compile(r"<answer>(.*?)</answer>", re.DOTALL)
    COORD_PATTERN = re.compile(
        r"\(\s*(\d+)\s*,\s*(\d+)\s*\)\s*,\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)"
    )

    def parse_bbox(coord_str: str):
        match = COORD_PATTERN.fullmatch(coord_str.strip())
        if not match:
            raise ValueError(f"Invalid bbox format: {coord_str}")
        x1, y1, x2, y2 = list(map(int, match.groups()))
        if x2 <= x1 or y2 <= y1:
            raise ValueError(f"Invalid bbox (x2<=x1 or y2<=y1): {coord_str}")
        return x1, y1, x2, y2
    
    try:
        # Extract <answer> content
        answer_match = ANSWER_PATTERN.search(predict)
        if not answer_match:
            return None

        answer_str = answer_match.group(1).strip()
        x1, y1, x2, y2 = parse_bbox(answer_str)
        pred_box = [x1, y1, x2, y2]

        return pred_box
    
    except Exception:
        return None
    
def format_reward(response: str) -> float:
    """
    Check whether the model output follows this format:
    <think> ... </think>
    <answer>(x1, y1), (x2, y2)</answer>
    """
    re_str = (
        r"<think>.*?</think>\s*"
        r"<answer>\s*\(\s*\d+\s*,\s*\d+\s*\)\s*,\s*\(\s*\d+\s*,\s*\d+\s*\)\s*</answer>"
    )
    pattern = re.compile(re_str, re.DOTALL)
    
    return 1.0 if pattern.search(response.strip()) else 0.0

    # return 1.0 if re.fullmatch(pattern, response.strip()) else 0.0

def compute_score(reward_inputs: list[dict[str, Any]], format_weight: float = 0.1, sam_model=None) -> list[dict[str, float]]:
    """
    Compute combined format + accuracy reward for batch inputs.
    Input:
        reward_inputs: list of dicts, each containing:
          {
            "response": "<think>...</think><answer>(x1,y1),(x2,y2)</answer>",
            "ground_truth": "[x1,y1,x2,y2]"
          }
    """
    if not isinstance(reward_inputs, list):
        raise ValueError("Please use `reward_type=batch` for math reward function.")

    if sam_model is None:
        sam_model = SAMWrapper(model_path="./third_party/sam2/checkpoints/sam2.1_hiera_large.pt")
    sm_calculator = Smeasure(alpha=0.5)

    scores = []
    for reward_input in reward_inputs:
        # normalize spacing (for qwen-style extra spaces)
        # response = re.sub(r"\s*(<|>|/)\s*", r"\1", reward_input["response"])
        response = re.sub(r">\s+<", "><", reward_input["response"])
        format_score = format_reward(response)

        pred_bbox = get_pred_bbox(response)
        if pred_bbox is not None:
            bbox_score = bbox_reward(pred_bbox, reward_input["ground_truth"])
            seg_score = seg_reward(pred_bbox, reward_input["ground_truth"], sam_model, sm_calculator)
        else:
            bbox_score = 0.0
            seg_score = 0.0
        overall = (1 - format_weight) * (bbox_score * 0.7 + seg_score * 0.3) + format_weight * format_score

        scores.append({
            "overall": overall,
            "format": format_score,
            "accuracy": bbox_score,
            "seg_score": seg_score
        })

    return scores